image:
  name: docker:latest
#  name: femtopixel/kompose:latest
#  entrypoint: [""]

services:
  - docker:dind

before_script:
#  - apk update
#  - apk add docker
  - mkdir /etc/docker/
  - 'echo "{ \"insecure-registries\" : [\"gitlab.miaounyan.eu:5005\"] }" > /etc/docker/daemon.json'
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN gitlab.miaounyan.eu:5005
  - docker info

build:
  stage: build
  script:
    - set -e
    - kompose up -v
