image:
  name: docker:latest
#  name: femtopixel/kompose:latest
#  entrypoint: [""]

services:
  - docker:dind

before_script:
  - apk update
  - apk add docker
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker info

build:
  stage: build
  script:
    - set -e
    - kompose up -v
