version: '3'

services:
  velibsoapwebapplication:
    image: gitlab.miaounyan.eu:5005/piernov/si4-ws-event
    ports:
      - "5050:5050"
    build:
      context: .
      dockerfile: VelibSoapWebApplication/Dockerfile

  velibsoapclientconsole:
    image: velibsoapclientconsole
    build:
      context: .
      dockerfile: VelibSoapClientConsole/Dockerfile
    tty: true
