//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VelibSoapClientWinForms
{
    namespace VelibSoapServiceReference
    {
        using System.Runtime.Serialization;
        using System;


        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name = "VelibSoapContract", Namespace = "http://tempuri.org/")]
        [System.SerializableAttribute()]
        public partial class VelibSoapContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        {

            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string NameField;

            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private VelibSoapServiceReference.ArrayOfString CitiesField;

            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string CommercialNameField;

            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string CountryCodeField;

            [global::System.ComponentModel.BrowsableAttribute(false)]
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData
            {
                get
                {
                    return this.extensionDataField;
                }
                set
                {
                    this.extensionDataField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
            public string Name
            {
                get
                {
                    return this.NameField;
                }
                set
                {
                    if ((object.ReferenceEquals(this.NameField, value) != true))
                    {
                        this.NameField = value;
                        this.RaisePropertyChanged("Name");
                    }
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
            public VelibSoapServiceReference.ArrayOfString Cities
            {
                get
                {
                    return this.CitiesField;
                }
                set
                {
                    if ((object.ReferenceEquals(this.CitiesField, value) != true))
                    {
                        this.CitiesField = value;
                        this.RaisePropertyChanged("Cities");
                    }
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
            public string CommercialName
            {
                get
                {
                    return this.CommercialNameField;
                }
                set
                {
                    if ((object.ReferenceEquals(this.CommercialNameField, value) != true))
                    {
                        this.CommercialNameField = value;
                        this.RaisePropertyChanged("CommercialName");
                    }
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
            public string CountryCode
            {
                get
                {
                    return this.CountryCodeField;
                }
                set
                {
                    if ((object.ReferenceEquals(this.CountryCodeField, value) != true))
                    {
                        this.CountryCodeField = value;
                        this.RaisePropertyChanged("CountryCode");
                    }
                }
            }

            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

            protected void RaisePropertyChanged(string propertyName)
            {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null))
                {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }

        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ArrayOfString", Namespace = "http://tempuri.org/", ItemName = "string")]
        [System.SerializableAttribute()]
        public class ArrayOfString : System.Collections.Generic.List<string>
        {
        }

        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name = "VelibSoapStation", Namespace = "http://tempuri.org/")]
        [System.SerializableAttribute()]
        public partial class VelibSoapStation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        {

            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

            private int NumberField;

            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string NameField;

            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string AddressField;

            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string ContractNameField;

            private int BikeStandsField;

            private int AvailableBikeStandsField;

            private int AvailableBikesField;

            [global::System.ComponentModel.BrowsableAttribute(false)]
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData
            {
                get
                {
                    return this.extensionDataField;
                }
                set
                {
                    this.extensionDataField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
            public int Number
            {
                get
                {
                    return this.NumberField;
                }
                set
                {
                    if ((this.NumberField.Equals(value) != true))
                    {
                        this.NumberField = value;
                        this.RaisePropertyChanged("Number");
                    }
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
            public string Name
            {
                get
                {
                    return this.NameField;
                }
                set
                {
                    if ((object.ReferenceEquals(this.NameField, value) != true))
                    {
                        this.NameField = value;
                        this.RaisePropertyChanged("Name");
                    }
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
            public string Address
            {
                get
                {
                    return this.AddressField;
                }
                set
                {
                    if ((object.ReferenceEquals(this.AddressField, value) != true))
                    {
                        this.AddressField = value;
                        this.RaisePropertyChanged("Address");
                    }
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
            public string ContractName
            {
                get
                {
                    return this.ContractNameField;
                }
                set
                {
                    if ((object.ReferenceEquals(this.ContractNameField, value) != true))
                    {
                        this.ContractNameField = value;
                        this.RaisePropertyChanged("ContractName");
                    }
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 4)]
            public int BikeStands
            {
                get
                {
                    return this.BikeStandsField;
                }
                set
                {
                    if ((this.BikeStandsField.Equals(value) != true))
                    {
                        this.BikeStandsField = value;
                        this.RaisePropertyChanged("BikeStands");
                    }
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 5)]
            public int AvailableBikeStands
            {
                get
                {
                    return this.AvailableBikeStandsField;
                }
                set
                {
                    if ((this.AvailableBikeStandsField.Equals(value) != true))
                    {
                        this.AvailableBikeStandsField = value;
                        this.RaisePropertyChanged("AvailableBikeStands");
                    }
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 6)]
            public int AvailableBikes
            {
                get
                {
                    return this.AvailableBikesField;
                }
                set
                {
                    if ((this.AvailableBikesField.Equals(value) != true))
                    {
                        this.AvailableBikesField = value;
                        this.RaisePropertyChanged("AvailableBikes");
                    }
                }
            }

            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

            protected void RaisePropertyChanged(string propertyName)
            {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null))
                {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
        [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "VelibSoapServiceReference.IVelibSoapService")]
        public interface IVelibSoapService
        {

            // CODEGEN : La génération du contrat de message depuis le nom d'élément GetContractsResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
            [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IVelibSoapService/GetContracts", ReplyAction = "*")]
            VelibSoapServiceReference.GetContractsResponse GetContracts(VelibSoapServiceReference.GetContractsRequest request);

            [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IVelibSoapService/GetContracts", ReplyAction = "*")]
            System.Threading.Tasks.Task<VelibSoapServiceReference.GetContractsResponse> GetContractsAsync(VelibSoapServiceReference.GetContractsRequest request);

            // CODEGEN : La génération du contrat de message depuis le nom d'élément contract de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
            [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IVelibSoapService/GetStations", ReplyAction = "*")]
            VelibSoapServiceReference.GetStationsResponse GetStations(VelibSoapServiceReference.GetStationsRequest request);

            [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IVelibSoapService/GetStations", ReplyAction = "*")]
            System.Threading.Tasks.Task<VelibSoapServiceReference.GetStationsResponse> GetStationsAsync(VelibSoapServiceReference.GetStationsRequest request);
        }

        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
        public partial class GetContractsRequest
        {

            [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetContracts", Namespace = "http://tempuri.org/", Order = 0)]
            public VelibSoapServiceReference.GetContractsRequestBody Body;

            public GetContractsRequest()
            {
            }

            public GetContractsRequest(VelibSoapServiceReference.GetContractsRequestBody Body)
            {
                this.Body = Body;
            }
        }

        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        [System.Runtime.Serialization.DataContractAttribute()]
        public partial class GetContractsRequestBody
        {

            public GetContractsRequestBody()
            {
            }
        }

        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
        public partial class GetContractsResponse
        {

            [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetContractsResponse", Namespace = "http://tempuri.org/", Order = 0)]
            public VelibSoapServiceReference.GetContractsResponseBody Body;

            public GetContractsResponse()
            {
            }

            public GetContractsResponse(VelibSoapServiceReference.GetContractsResponseBody Body)
            {
                this.Body = Body;
            }
        }

        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
        public partial class GetContractsResponseBody
        {

            [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
            public VelibSoapServiceReference.VelibSoapContract[] GetContractsResult;

            public GetContractsResponseBody()
            {
            }

            public GetContractsResponseBody(VelibSoapServiceReference.VelibSoapContract[] GetContractsResult)
            {
                this.GetContractsResult = GetContractsResult;
            }
        }

        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
        public partial class GetStationsRequest
        {

            [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetStations", Namespace = "http://tempuri.org/", Order = 0)]
            public VelibSoapServiceReference.GetStationsRequestBody Body;

            public GetStationsRequest()
            {
            }

            public GetStationsRequest(VelibSoapServiceReference.GetStationsRequestBody Body)
            {
                this.Body = Body;
            }
        }

        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
        public partial class GetStationsRequestBody
        {

            [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
            public VelibSoapServiceReference.VelibSoapContract contract;

            public GetStationsRequestBody()
            {
            }

            public GetStationsRequestBody(VelibSoapServiceReference.VelibSoapContract contract)
            {
                this.contract = contract;
            }
        }

        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
        public partial class GetStationsResponse
        {

            [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetStationsResponse", Namespace = "http://tempuri.org/", Order = 0)]
            public VelibSoapServiceReference.GetStationsResponseBody Body;

            public GetStationsResponse()
            {
            }

            public GetStationsResponse(VelibSoapServiceReference.GetStationsResponseBody Body)
            {
                this.Body = Body;
            }
        }

        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
        public partial class GetStationsResponseBody
        {

            [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
            public VelibSoapServiceReference.VelibSoapStation[] GetStationsResult;

            public GetStationsResponseBody()
            {
            }

            public GetStationsResponseBody(VelibSoapServiceReference.VelibSoapStation[] GetStationsResult)
            {
                this.GetStationsResult = GetStationsResult;
            }
        }

        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
        public interface IVelibSoapServiceChannel : VelibSoapServiceReference.IVelibSoapService, System.ServiceModel.IClientChannel
        {
        }

        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
        public partial class VelibSoapServiceClient : System.ServiceModel.ClientBase<VelibSoapServiceReference.IVelibSoapService>, VelibSoapServiceReference.IVelibSoapService
        {

            public VelibSoapServiceClient()
            {
            }

            public VelibSoapServiceClient(string endpointConfigurationName) :
                    base(endpointConfigurationName)
            {
            }

            public VelibSoapServiceClient(string endpointConfigurationName, string remoteAddress) :
                    base(endpointConfigurationName, remoteAddress)
            {
            }

            public VelibSoapServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                    base(endpointConfigurationName, remoteAddress)
            {
            }

            public VelibSoapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                    base(binding, remoteAddress)
            {
            }

            [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
            VelibSoapServiceReference.GetContractsResponse VelibSoapServiceReference.IVelibSoapService.GetContracts(VelibSoapServiceReference.GetContractsRequest request)
            {
                return base.Channel.GetContracts(request);
            }

            public VelibSoapServiceReference.VelibSoapContract[] GetContracts()
            {
                VelibSoapServiceReference.GetContractsRequest inValue = new VelibSoapServiceReference.GetContractsRequest();
                inValue.Body = new VelibSoapServiceReference.GetContractsRequestBody();
                VelibSoapServiceReference.GetContractsResponse retVal = ((VelibSoapServiceReference.IVelibSoapService)(this)).GetContracts(inValue);
                return retVal.Body.GetContractsResult;
            }

            [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
            System.Threading.Tasks.Task<VelibSoapServiceReference.GetContractsResponse> VelibSoapServiceReference.IVelibSoapService.GetContractsAsync(VelibSoapServiceReference.GetContractsRequest request)
            {
                return base.Channel.GetContractsAsync(request);
            }

            public System.Threading.Tasks.Task<VelibSoapServiceReference.GetContractsResponse> GetContractsAsync()
            {
                VelibSoapServiceReference.GetContractsRequest inValue = new VelibSoapServiceReference.GetContractsRequest();
                inValue.Body = new VelibSoapServiceReference.GetContractsRequestBody();
                return ((VelibSoapServiceReference.IVelibSoapService)(this)).GetContractsAsync(inValue);
            }

            [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
            VelibSoapServiceReference.GetStationsResponse VelibSoapServiceReference.IVelibSoapService.GetStations(VelibSoapServiceReference.GetStationsRequest request)
            {
                return base.Channel.GetStations(request);
            }

            public VelibSoapServiceReference.VelibSoapStation[] GetStations(VelibSoapServiceReference.VelibSoapContract contract)
            {
                VelibSoapServiceReference.GetStationsRequest inValue = new VelibSoapServiceReference.GetStationsRequest();
                inValue.Body = new VelibSoapServiceReference.GetStationsRequestBody();
                inValue.Body.contract = contract;
                VelibSoapServiceReference.GetStationsResponse retVal = ((VelibSoapServiceReference.IVelibSoapService)(this)).GetStations(inValue);
                return retVal.Body.GetStationsResult;
            }

            [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
            System.Threading.Tasks.Task<VelibSoapServiceReference.GetStationsResponse> VelibSoapServiceReference.IVelibSoapService.GetStationsAsync(VelibSoapServiceReference.GetStationsRequest request)
            {
                return base.Channel.GetStationsAsync(request);
            }

            public System.Threading.Tasks.Task<VelibSoapServiceReference.GetStationsResponse> GetStationsAsync(VelibSoapServiceReference.VelibSoapContract contract)
            {
                VelibSoapServiceReference.GetStationsRequest inValue = new VelibSoapServiceReference.GetStationsRequest();
                inValue.Body = new VelibSoapServiceReference.GetStationsRequestBody();
                inValue.Body.contract = contract;
                return ((VelibSoapServiceReference.IVelibSoapService)(this)).GetStationsAsync(inValue);
            }
        }
    }
}