//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VelibSoapClientConsole.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VelibSoapContract", Namespace="http://schemas.datacontract.org/2004/07/VelibSoapServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class VelibSoapContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] CitiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommercialNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Cities {
            get {
                return this.CitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.CitiesField, value) != true)) {
                    this.CitiesField = value;
                    this.RaisePropertyChanged("Cities");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CommercialName {
            get {
                return this.CommercialNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CommercialNameField, value) != true)) {
                    this.CommercialNameField = value;
                    this.RaisePropertyChanged("CommercialName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryCode {
            get {
                return this.CountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryCodeField, value) != true)) {
                    this.CountryCodeField = value;
                    this.RaisePropertyChanged("CountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VelibSoapStation", Namespace="http://schemas.datacontract.org/2004/07/VelibSoapServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class VelibSoapStation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AvailableBikeStandsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AvailableBikesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BikeStandsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContractNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AvailableBikeStands {
            get {
                return this.AvailableBikeStandsField;
            }
            set {
                if ((this.AvailableBikeStandsField.Equals(value) != true)) {
                    this.AvailableBikeStandsField = value;
                    this.RaisePropertyChanged("AvailableBikeStands");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AvailableBikes {
            get {
                return this.AvailableBikesField;
            }
            set {
                if ((this.AvailableBikesField.Equals(value) != true)) {
                    this.AvailableBikesField = value;
                    this.RaisePropertyChanged("AvailableBikes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BikeStands {
            get {
                return this.BikeStandsField;
            }
            set {
                if ((this.BikeStandsField.Equals(value) != true)) {
                    this.BikeStandsField = value;
                    this.RaisePropertyChanged("BikeStands");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContractName {
            get {
                return this.ContractNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ContractNameField, value) != true)) {
                    this.ContractNameField = value;
                    this.RaisePropertyChanged("ContractName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MarshalByRefObject", Namespace="http://schemas.datacontract.org/2004/07/System")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VelibSoapClientConsole.ServiceReference1.Component))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VelibSoapClientConsole.ServiceReference1.Timer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(string[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VelibSoapClientConsole.ServiceReference1.VelibSoapContract[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VelibSoapClientConsole.ServiceReference1.VelibSoapContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VelibSoapClientConsole.ServiceReference1.VelibSoapStation[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VelibSoapClientConsole.ServiceReference1.VelibSoapStation))]
    public partial class MarshalByRefObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private object @__identityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public object @__identity {
            get {
                return this.@__identityField;
            }
            set {
                if ((object.ReferenceEquals(this.@__identityField, value) != true)) {
                    this.@__identityField = value;
                    this.RaisePropertyChanged("__identity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Component", Namespace="http://schemas.datacontract.org/2004/07/System.ComponentModel")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VelibSoapClientConsole.ServiceReference1.Timer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(string[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VelibSoapClientConsole.ServiceReference1.MarshalByRefObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VelibSoapClientConsole.ServiceReference1.VelibSoapContract[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VelibSoapClientConsole.ServiceReference1.VelibSoapContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VelibSoapClientConsole.ServiceReference1.VelibSoapStation[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VelibSoapClientConsole.ServiceReference1.VelibSoapStation))]
    public partial class Component : VelibSoapClientConsole.ServiceReference1.MarshalByRefObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object SiteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Site {
            get {
                return this.SiteField;
            }
            set {
                if ((object.ReferenceEquals(this.SiteField, value) != true)) {
                    this.SiteField = value;
                    this.RaisePropertyChanged("Site");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Timer", Namespace="http://schemas.datacontract.org/2004/07/System.Timers")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VelibSoapClientConsole.ServiceReference1.Component))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(string[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VelibSoapClientConsole.ServiceReference1.MarshalByRefObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VelibSoapClientConsole.ServiceReference1.VelibSoapContract[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VelibSoapClientConsole.ServiceReference1.VelibSoapContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VelibSoapClientConsole.ServiceReference1.VelibSoapStation[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VelibSoapClientConsole.ServiceReference1.VelibSoapStation))]
    public partial class Timer : VelibSoapClientConsole.ServiceReference1.Component {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AutoResetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double IntervalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object SynchronizingObjectField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AutoReset {
            get {
                return this.AutoResetField;
            }
            set {
                if ((this.AutoResetField.Equals(value) != true)) {
                    this.AutoResetField = value;
                    this.RaisePropertyChanged("AutoReset");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Enabled {
            get {
                return this.EnabledField;
            }
            set {
                if ((this.EnabledField.Equals(value) != true)) {
                    this.EnabledField = value;
                    this.RaisePropertyChanged("Enabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Interval {
            get {
                return this.IntervalField;
            }
            set {
                if ((this.IntervalField.Equals(value) != true)) {
                    this.IntervalField = value;
                    this.RaisePropertyChanged("Interval");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object SynchronizingObject {
            get {
                return this.SynchronizingObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SynchronizingObjectField, value) != true)) {
                    this.SynchronizingObjectField = value;
                    this.RaisePropertyChanged("SynchronizingObject");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IVelibSoapService", CallbackContract=typeof(VelibSoapClientConsole.ServiceReference1.IVelibSoapServiceCallback))]
    public interface IVelibSoapService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibSoapService/GetContracts", ReplyAction="http://tempuri.org/IVelibSoapService/GetContractsResponse")]
        VelibSoapClientConsole.ServiceReference1.VelibSoapContract[] GetContracts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibSoapService/GetContracts", ReplyAction="http://tempuri.org/IVelibSoapService/GetContractsResponse")]
        System.Threading.Tasks.Task<VelibSoapClientConsole.ServiceReference1.VelibSoapContract[]> GetContractsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibSoapService/GetContractsName", ReplyAction="http://tempuri.org/IVelibSoapService/GetContractsNameResponse")]
        string[] GetContractsName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibSoapService/GetContractsName", ReplyAction="http://tempuri.org/IVelibSoapService/GetContractsNameResponse")]
        System.Threading.Tasks.Task<string[]> GetContractsNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibSoapService/GetContractByName", ReplyAction="http://tempuri.org/IVelibSoapService/GetContractByNameResponse")]
        VelibSoapClientConsole.ServiceReference1.VelibSoapContract GetContractByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibSoapService/GetContractByName", ReplyAction="http://tempuri.org/IVelibSoapService/GetContractByNameResponse")]
        System.Threading.Tasks.Task<VelibSoapClientConsole.ServiceReference1.VelibSoapContract> GetContractByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibSoapService/GetStations", ReplyAction="http://tempuri.org/IVelibSoapService/GetStationsResponse")]
        VelibSoapClientConsole.ServiceReference1.VelibSoapStation[] GetStations(VelibSoapClientConsole.ServiceReference1.VelibSoapContract contract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibSoapService/GetStations", ReplyAction="http://tempuri.org/IVelibSoapService/GetStationsResponse")]
        System.Threading.Tasks.Task<VelibSoapClientConsole.ServiceReference1.VelibSoapStation[]> GetStationsAsync(VelibSoapClientConsole.ServiceReference1.VelibSoapContract contract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibSoapService/GetStationsName", ReplyAction="http://tempuri.org/IVelibSoapService/GetStationsNameResponse")]
        string[] GetStationsName(VelibSoapClientConsole.ServiceReference1.VelibSoapContract contract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibSoapService/GetStationsName", ReplyAction="http://tempuri.org/IVelibSoapService/GetStationsNameResponse")]
        System.Threading.Tasks.Task<string[]> GetStationsNameAsync(VelibSoapClientConsole.ServiceReference1.VelibSoapContract contract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibSoapService/GetStationByName", ReplyAction="http://tempuri.org/IVelibSoapService/GetStationByNameResponse")]
        VelibSoapClientConsole.ServiceReference1.VelibSoapStation GetStationByName(VelibSoapClientConsole.ServiceReference1.VelibSoapContract contract, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibSoapService/GetStationByName", ReplyAction="http://tempuri.org/IVelibSoapService/GetStationByNameResponse")]
        System.Threading.Tasks.Task<VelibSoapClientConsole.ServiceReference1.VelibSoapStation> GetStationByNameAsync(VelibSoapClientConsole.ServiceReference1.VelibSoapContract contract, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibSoapService/SubscribeAvailableVelibUpdatedEvent", ReplyAction="http://tempuri.org/IVelibSoapService/SubscribeAvailableVelibUpdatedEventResponse")]
        VelibSoapClientConsole.ServiceReference1.Timer SubscribeAvailableVelibUpdatedEvent(VelibSoapClientConsole.ServiceReference1.VelibSoapContract contract, string name, int period);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibSoapService/SubscribeAvailableVelibUpdatedEvent", ReplyAction="http://tempuri.org/IVelibSoapService/SubscribeAvailableVelibUpdatedEventResponse")]
        System.Threading.Tasks.Task<VelibSoapClientConsole.ServiceReference1.Timer> SubscribeAvailableVelibUpdatedEventAsync(VelibSoapClientConsole.ServiceReference1.VelibSoapContract contract, string name, int period);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVelibSoapServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IVelibSoapService/AvailableVelibUpdated")]
        void AvailableVelibUpdated(VelibSoapClientConsole.ServiceReference1.VelibSoapStation station, int newValue);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVelibSoapServiceChannel : VelibSoapClientConsole.ServiceReference1.IVelibSoapService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VelibSoapServiceClient : System.ServiceModel.DuplexClientBase<VelibSoapClientConsole.ServiceReference1.IVelibSoapService>, VelibSoapClientConsole.ServiceReference1.IVelibSoapService {
        
        public VelibSoapServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public VelibSoapServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public VelibSoapServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public VelibSoapServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public VelibSoapServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public VelibSoapClientConsole.ServiceReference1.VelibSoapContract[] GetContracts() {
            return base.Channel.GetContracts();
        }
        
        public System.Threading.Tasks.Task<VelibSoapClientConsole.ServiceReference1.VelibSoapContract[]> GetContractsAsync() {
            return base.Channel.GetContractsAsync();
        }
        
        public string[] GetContractsName() {
            return base.Channel.GetContractsName();
        }
        
        public System.Threading.Tasks.Task<string[]> GetContractsNameAsync() {
            return base.Channel.GetContractsNameAsync();
        }
        
        public VelibSoapClientConsole.ServiceReference1.VelibSoapContract GetContractByName(string name) {
            return base.Channel.GetContractByName(name);
        }
        
        public System.Threading.Tasks.Task<VelibSoapClientConsole.ServiceReference1.VelibSoapContract> GetContractByNameAsync(string name) {
            return base.Channel.GetContractByNameAsync(name);
        }
        
        public VelibSoapClientConsole.ServiceReference1.VelibSoapStation[] GetStations(VelibSoapClientConsole.ServiceReference1.VelibSoapContract contract) {
            return base.Channel.GetStations(contract);
        }
        
        public System.Threading.Tasks.Task<VelibSoapClientConsole.ServiceReference1.VelibSoapStation[]> GetStationsAsync(VelibSoapClientConsole.ServiceReference1.VelibSoapContract contract) {
            return base.Channel.GetStationsAsync(contract);
        }
        
        public string[] GetStationsName(VelibSoapClientConsole.ServiceReference1.VelibSoapContract contract) {
            return base.Channel.GetStationsName(contract);
        }
        
        public System.Threading.Tasks.Task<string[]> GetStationsNameAsync(VelibSoapClientConsole.ServiceReference1.VelibSoapContract contract) {
            return base.Channel.GetStationsNameAsync(contract);
        }
        
        public VelibSoapClientConsole.ServiceReference1.VelibSoapStation GetStationByName(VelibSoapClientConsole.ServiceReference1.VelibSoapContract contract, string name) {
            return base.Channel.GetStationByName(contract, name);
        }
        
        public System.Threading.Tasks.Task<VelibSoapClientConsole.ServiceReference1.VelibSoapStation> GetStationByNameAsync(VelibSoapClientConsole.ServiceReference1.VelibSoapContract contract, string name) {
            return base.Channel.GetStationByNameAsync(contract, name);
        }
        
        public VelibSoapClientConsole.ServiceReference1.Timer SubscribeAvailableVelibUpdatedEvent(VelibSoapClientConsole.ServiceReference1.VelibSoapContract contract, string name, int period) {
            return base.Channel.SubscribeAvailableVelibUpdatedEvent(contract, name, period);
        }
        
        public System.Threading.Tasks.Task<VelibSoapClientConsole.ServiceReference1.Timer> SubscribeAvailableVelibUpdatedEventAsync(VelibSoapClientConsole.ServiceReference1.VelibSoapContract contract, string name, int period) {
            return base.Channel.SubscribeAvailableVelibUpdatedEventAsync(contract, name, period);
        }
    }
}
